version: "2"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mysql_master:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=kafka
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "8080:3306"
    volumes:
      - db:/var/lib/mysql
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

  # mysql_slave:
  #   image: mysql:8.0
  #   env_file:
  #     - ./slave/mysql_slave.env
  #   container_name: "mysql_slave"
  #   restart: "no"
  #   ports:
  #     - 5506:3306
  #   depends_on:
  #     - mysql_master
  #   volumes:
  #     - ./slave/conf/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
  #     - ./slave/data:/var/lib/mysql
  #   networks:
  #     - overlay

volumes:
  db:
    driver: local
  cache:
    driver: local
